version: '3.9'

services:
  
  # DC1
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_BROKER_RACK: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka1:19092,EXTERNAL://localhost:9091
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  
  # DC1
  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_BROKER_RACK: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka2:19092,EXTERNAL://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  
  # DC1    
  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_BROKER_RACK: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka3:19092,EXTERNAL://localhost:9093
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  # DC2    
  kafka4:
    image: bitnami/kafka:latest
    container_name: kafka4
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_CFG_BROKER_RACK: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka4:19092,EXTERNAL://localhost:9094
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  
  # DC2
  kafka5:
    image: bitnami/kafka:latest
    container_name: kafka5
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_CFG_BROKER_RACK: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka5:19092,EXTERNAL://localhost:9095
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  
  # DC2
  kafka6:
    image: bitnami/kafka:latest
    container_name: kafka6
    ports:
      - "9096:9096"
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_CFG_BROKER_RACK: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:19092,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka6:19092,EXTERNAL://localhost:9096
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  # Zookeeper Services
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
     - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181


# brokers reachable from host at: localhost:9091,localhost:9092,localhost:9093,localhost:9094,localhost:9095,localhost:9096
