version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifi
  nifi01:
    container_name: nifi01
    image: apache/nifi:latest
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8081
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_ELECTION_MAX_CANDIDATES=2
      - NIFI_SENSITIVE_PROPS_KEY=abcdefgh123456789
    volumes:
      - nifi01_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi01_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi01_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi01_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi01_conf:/opt/nifi/nifi-current/conf
      - nifi01_state:/opt/nifi/nifi-current/state
      - nifi01_logs:/opt/nifi/nifi-current/logs
      - nifi01_data:/opt/nifi/nifi-current/data
      - type: bind
        source: 'C:\Users\Muham\Documents\Projects\nifi-drivers'
        target: /opt/nifi/nifi-current/drivers
    networks:
      - nifi

  nifi02:
    container_name: nifi02
    image: apache/nifi:latest
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8081
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_ELECTION_MAX_CANDIDATES=2
      - NIFI_SENSITIVE_PROPS_KEY=abcdefgh123456789
    volumes:
      - nifi02_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi02_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi02_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi02_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi02_conf:/opt/nifi/nifi-current/conf
      - nifi02_state:/opt/nifi/nifi-current/state
      - nifi02_logs:/opt/nifi/nifi-current/logs
      - nifi02_data:/opt/nifi/nifi-current/data
      - type: bind
        source: 'C:\Users\Muham\Documents\Projects\nifi-drivers'
        target: /opt/nifi/nifi-current/drivers
    networks:
      - nifi

  nifi03:
    container_name: nifi03
    image: apache/nifi:latest
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8081
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_ELECTION_MAX_CANDIDATES=2
      - NIFI_SENSITIVE_PROPS_KEY=abcdefgh123456789
    volumes:
      - nifi03_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi03_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi03_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi03_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi03_conf:/opt/nifi/nifi-current/conf
      - nifi03_state:/opt/nifi/nifi-current/state
      - nifi03_logs:/opt/nifi/nifi-current/logs
      - nifi03_data:/opt/nifi/nifi-current/data
      - type: bind
        source: 'C:\Users\Muham\Documents\Projects\nifi-drivers'
        target: /opt/nifi/nifi-current/drivers
    networks:
      - nifi

volumes:
  nifi01_content_repository:
    driver: local
  nifi01_database_repository:
    driver: local
  nifi01_flowfile_repository:
    driver: local
  nifi01_provenance_repository:
    driver: local
  nifi01_conf:
    driver: local
  nifi01_state:
    driver: local
  nifi01_logs:
    driver: local
  nifi01_data:
    driver: local

  nifi02_content_repository:
    driver: local
  nifi02_database_repository:
    driver: local
  nifi02_flowfile_repository:
    driver: local
  nifi02_provenance_repository:
    driver: local
  nifi02_conf:
    driver: local
  nifi02_state:
    driver: local
  nifi02_logs:
    driver: local
  nifi02_data:
    driver: local

  nifi03_content_repository:
    driver: local
  nifi03_database_repository:
    driver: local
  nifi03_flowfile_repository:
    driver: local
  nifi03_provenance_repository:
    driver: local
  nifi03_conf:
    driver: local
  nifi03_state:
    driver: local
  nifi03_logs:
    driver: local
  nifi03_data:
    driver: local

networks:
  nifi:
    driver: bridge
