version: "2"
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "sample_topic:1:1"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - kafka:/kafka
    networks:
      - nificluster_nifi

networks:
  nificluster_nifi:
    external: true
volumes:
  kafka:
    driver: local
